# Generated by Django 5.2 on 2025-04-04 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_design', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DesignRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prompt', models.TextField(blank=True)),
                ('input_image', models.ImageField(blank=True, null=True, upload_to='input_images/')),
                ('output_image', models.ImageField(blank=True, null=True, upload_to='output_images/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
